### ISSUE TITLE
Proper configuration of device levels

### ISSUE THREAD

**Issue by OnkelTem** [DanielRapp/doppler#10]
Glad to see such a nice idea implemented!
I came from this page: https://danielrapp.github.io/doppler/
I own a PC where camera with mic is plugged as usually - at the top of the [middle] screen. 
When in page-scroll mode I move my hand, page scrolls down, but when I move hand back - it scrolls upward to the same interval.
I think this is related to either camera/speakers position or their levels.
What do you recommend to tweak?

**Comment by thanhtranhd** [comment]
You could try moving your hand slower on the direction that you don't want to scroll. For example in your case, moving your hand toward the screen slowly wouldn't scroll the screen up
