### ISSUE TITLE
Tone suddenly disappears, high frequencies don't work in other tabs and applications anymore

### ISSUE THREAD

**Issue by thisancog** [DanielRapp/doppler#15]
I played with the doppler tool a bit, when suddenly the once clearly audible tone disappeared and the motion tracking didn't work anymore. I didn't think much of it, but now, even after a restart, the higher frequencies on any other website and application don't work anymore. Does the tool actively block the frequency or is it likely, that my speakers are broken?

**Comment by thisancog** [comment]
I work on an late 2013 iMac, OS X Yosemite 10.10.5, latest Chrome version. Audio and MIDI preferences are unobtrusive. Neither sudo killall coreaudiod nor resetting PRAM worked. The high frequencies are just cut away (or at least very quiet), no matter which program I use, no matter how often I restart my system. It all sounds like one muzzled the speaker with a blanket.
EDIT: I just tried my headphones. They work perfectly. The problem is occurs only with the internal speaker (or the software that handles it).

**Comment by DanielRapp** [comment]
The tool does not actively block frequencies. I've not heard this happen before! Strage!
