### ISSUE TITLE
Demo Url does not work

### ISSUE THREAD

**Issue by yaworsw** [DanielRapp/doppler#16]
I was showing this to some people the other day and ran into a small issue getting it to work.

It turns out `getUserMedia()` doesn't work from non `https://` urls.  

![image](https://cloud.githubusercontent.com/assets/3655406/12437658/b5283216-beed-11e5-91c3-9c19e2bfee55.png)

Luckily the fix is as easy as changing the website for this repository to `https://danielrapp.github.io/doppler/`

**Comment by DanielRapp** [comment]
Oh my, thanks!
