### ISSUE TITLE
Link to Paper is broken

### ISSUE THREAD

**Issue by theoomoregbee** [DanielRapp/doppler#18]

**Comment by theoomoregbee** [comment]
http://research.microsoft.com/en-us/um/redmond/groups/cue/publications/guptasoundwavechi2012.pdf here the link that's broken

**Comment by WuTianming** [comment]
https://www.microsoft.com/en-us/research/publication/soundwave-using-doppler-effect-sense-gestures/

https://www.microsoft.com/en-us/research/project/soundwave-using-the-doppler-effect-to-sense-gestures/

the relevant pages here (but the pdf file is nowhere to find)

**Comment by WuTianming** [comment]
Alright I found the original paper here

https://www.microsoft.com/en-us/research/wp-content/uploads/2016/11/GuptaSoundWaveCHI2012.pdf

**Comment by theoomoregbee** [comment]
Thanks
