### ISSUE TITLE
Lot of noise and flickering

### ISSUE THREAD

**Issue by shivendrasoni** [DanielRapp/doppler#5]
I am getting a lot of noise and flickering. 

Basically I am unable to use the library. I had to turn of noise cancellation for it to start giving noisy readings. But switching it on, renders it useless.

**Comment by thanhtranhd** [comment]
I also have this problem. Not sure what causes it yet. Maybe too much background noise or the mics are too sensitive?

**Comment by DanielAndreasen** [comment]
I played a bit with it on the web page, and had the same problem. Turning down for the sensitivity of the mic fixed it.

**Comment by thanhtranhd** [comment]
Thanks Daniel. It turned out my mic was having boost option. Turning boost off help. It's amazing to see a small movement of the hand can be registered with this method.

**Comment by DanielAndreasen** [comment]
You are welcome :)
"Science, it works bitches" -- Richard Dawkins

**Comment by davidmoseler** [comment]
But we want this to work on anyone's PC/cell phone, right? Then we can't just rely on client side configuration of each one's microphone. I think it is still an open issue: having server side cancellation of noise.

In a related topic, coughing, blowing and other sounds make pronounced waves in the ~20KHz range, and the program can't differentiate that from movement. In a way, it is entertaining that you can cough and make your page go up or down, but voice and sound detection is a different matter than movement detection. So, as the noise, it is a problem of differentiating doppler-generated frequencies from other sounds.
