### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by dataliven** [DanielRapp/doppler#6]
I'm trying the demo, got the following errors in browser console, unable to get it work. Please advise if any browser compatibility req. thx.

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://danielrapp.github.io').
13www-widgetapi.js:27 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://danielrapp.github.io').
www-embed-player.js:166 GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILED
www-widgetapi.js:27 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://danielrapp.github.io').
www-embed-player.js:166 GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED
5www-widgetapi.js:27 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://danielrapp.github.io').
www-embed-player.js:166 GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED
www-embed-player.js:166 GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED

**Comment by rafalsobota** [comment]
I can't run examples from http://danielrapp.github.io/doppler/ and locally from example.html on my Mac Mini with Chrome.

At http://danielrapp.github.io/doppler/ I allow to use microphone but nothing works. When I run example.html locally browser doesn't ask for permission and nothing works as well.

**Comment by DanielRapp** [comment]
@dataliven re: browser compatibility. It unfortunately only works on Chrome.

**Comment by DanielRapp** [comment]
@rafalsobota Does the frequency spectrum react to sound at all, or is the two visualizations in the "Measuring the doppler effect" section all blank? Please send a pic of it, like I have below
![screenshot 2015-03-12 18 38 42](https://cloud.githubusercontent.com/assets/442870/6624040/0ecb4824-c8e7-11e4-9750-347b57e9a763.png)

**Comment by rafalsobota** [comment]
@DanielRapp Excuse my stupidity, I though I have built-in microphone. Next I tried with headset, tuned mic and headphones volumes and frequency spectrum moved a bit, but not much and examples doesn't work. I'll try on laptop. I tried also Chrome for iPhone but after clicking on button "Press to see the effect of a 20 kHz tone, after it has bounced around the room" nothing happens.

**Comment by DanielRapp** [comment]
Yeah, it doesn't work on the iPhone, mic input with the Web Audio API isn't supported.
